input_data_path: "data/raw/heart_cleveland_upload.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
train_dataframe_path: "data/raw/predict_dataset.csv"
split_params:
  test_size: 0.2
  random_state: 5
train_params:
  model_type: "RandomForestClassifier"
  random_state: 5
feature_params:
  numerical_features:
    - "age"
    - "sex"
    - "cp"
    - "trestbps"
    - "chol"
    - "fbs"
    - "restecg"
    - "thalach"
    - "exang"
    - "oldpeak"
    - "slope"
    - 'ca'
    - 'thal'
  target_col: "condition"